export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    GALLERY: '/gallery',
    API_CONFIG: '/api-config',
    AI_CHAT: '/ai-chat',
    NOTICES: '/notices',
    LEADERSHIP: '/leadership',
    ABOUT: '/about',
    CONTACT: '/contact',
    VERIFY: '/verify',
  },
  AUTH: {
    STUDENT_LOGIN: '/student-login',
    TEACHER_LOGIN: '/teacher-login',
    PARENT_LOGIN: '/parent/login',
    ADMIN_LOGIN: '/rsbs-admin-access',
    VERIFY: '/auth/verify',
    VERIFY_OTP: '/verify-otp',
    VERIFY_PIN: '/verify-pin',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    CLASSES: '/admin/classes',
    SCHOOL_HOME: '/admin/school-home',
    STUDENTS: '/admin/students',
    ALUMNI: '/admin/alumni',
    TEACHERS: '/admin/teachers',
    PARENTS: '/admin/parents',
    PARENT_DETAIL: (id: string) => `/admin/parents/${id}`,
    FEES: '/admin/fees',
    ATTENDANCE: '/admin/attendance',
    TIMETABLE: '/admin/timetable',
    EXAMS: '/admin/exams',
    NOTICES: '/admin/notices',
    QUERIES: '/admin/queries',
    GALLERY: '/admin/gallery',
    TEMPLATES: '/admin/templates',
    CERTIFICATES: '/admin/certificates',
    BRANDING: '/admin/branding',
    AI_MANAGEMENT: '/admin/ai-management',
    BACKUP: '/admin/backup',
    API_MANAGEMENT: '/admin/api-management',
    ADMIN_MANAGEMENT: '/admin/admin-management',
    ADMISSIONS: '/admin/admissions',
    APPOINTMENTS: '/admin/appointments',
    SEARCH: '/admin/search',
    LOGIN_INTEGRATION: '/admin/login-integration',
    QUIZ: '/admin/quizzes',
    QUIZ_CREATE: '/admin/quizzes/create',
    QUIZ_EDIT: (id: string) => `/admin/quizzes/${id}`,
    QUIZ_IMPORT: (id: string) => `/admin/quizzes/${id}/import`,
    QUIZ_ANALYTICS: (id: string) => `/admin/quizzes/${id}/analytics`,
    QUIZ_PREVIEW: (id: string) => `/admin/quizzes/${id}/preview`,
    STUDENT_PANEL_CONTENT: '/admin/student-panel-content',
  },
  STUDENT: {
    DASHBOARD: '/student',
    QUIZ: '/student/quizzes',
    QUIZ_PLAYER: (id: string) => `/student/quizzes/${id}/play`,
    QUIZ_RESULT: (id: string) => `/student/quizzes/result/${id}`,
    ATTENDANCE: '/student/attendance',
    TIMETABLE: '/student/timetable',
    STUDY_AI: '/student/study-ai',
    FEES: '/student/fees',
    EXAMS: '/student/exams',
    NOTICES: '/student/notices',
    GALLERY: '/student/gallery',
    QUERIES: '/student/queries',
    MORE: '/student/more',
    SETTINGS: '/student/settings',
    NOTIFICATION_SETTINGS: '/student/notifications',
    HELP_SUPPORT: '/student/help-support',
    PRIVACY_POLICY: '/student/privacy-policy',
    // Fallbacks for missing pages
    PROFILE: '/student',
  },
  TEACHER: {
    DASHBOARD: '/teacher',
    ATTENDANCE: '/teacher/attendance',
    TIMETABLE: '/teacher/timetable',
    NOTICES: '/teacher/notices',
    QUERIES: '/teacher/queries',
    PROFILE: '/teacher/profile',
    MARK_ATTENDANCE: (classId: string, sectionId: string) => `/teacher/mark-attendance/${classId}/${sectionId}`,
    // Fallbacks
    SETTINGS: '/teacher/profile',
  },
  PARENT: {
    DASHBOARD: '/parent/dashboard',
    ATTENDANCE: '/parent/attendance',
    FEES: '/parent/fees',
    PROFILE: '/parent/profile',
    MORE: '/parent/more',
    // Fallbacks
    SETTINGS: '/parent/profile',
  },
} as const;
